//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'field.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class Field extends _Field {
  //
  //
  //

  static const K_FIELD_NAME = 'fieldName';
  static const K_FIELD_TYPE = 'fieldType';
  static const K_NULLABLE = 'nullable';

  static const CLASS = 'Field';

  @override
  String get $class => CLASS;

  final String? fieldName;
  final String? fieldType;
  final bool? nullable;

  //
  //
  //

  const Field({
    required this.fieldName,
    required this.fieldType,
    this.nullable,
  });

  //
  //
  //

  factory Field.b({
    String? fieldName,
    String? fieldType,
    bool? nullable,
  }) {
    assert(fieldName != null);
    assert(fieldType != null);

    return Field(
      fieldName: fieldName,
      fieldType: fieldType,
      nullable: nullable,
    );
  }

  //
  //
  //

  factory Field.from(
    Model? other,
  ) {
    try {
      return fromOrNull(other)!;
    } catch (e) {
      assert(false, 'Field.from: $e');
      rethrow;
    }
  }

  static Field? fromOrNull(
    Model? other,
  ) {
    return fromJsonOrNull(other?.toJson())!;
  }

  //
  //
  //

  factory Field.of(
    Field other,
  ) {
    try {
      return ofOrNull(other)!;
    } catch (e) {
      assert(false, 'Field.of: $e');
      rethrow;
    }
  }

  static Field? ofOrNull(
    Field? other,
  ) {
    return fromJsonOrNull(other?.toJson());
  }

  //
  //
  //

  factory Field.fromJsonString(
    String source,
  ) {
    try {
      return fromJsonStringOrNull(source)!;
    } catch (e) {
      assert(false, 'Field.fromJsonString: $e');
      rethrow;
    }
  }

  static Field? fromJsonStringOrNull(
    String? source,
  ) {
    try {
      if (source!.isNotEmpty) {
        final decoded = jsonDecode(source);
        return Field.fromJson(decoded);
      } else {
        return Field.b();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  factory Field.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return fromJsonOrNull(otherData)!;
    } catch (e) {
      assert(false, 'Field.fromJson: $e');
      rethrow;
    }
  }

  static Field? fromJsonOrNull(
    Map<String, dynamic>? otherData,
  ) {
    try {
      final fieldName0 = otherData?[K_FIELD_NAME];
      final fieldName = fieldName0?.toString().trim().nullIfEmpty;
      final fieldType0 = otherData?[K_FIELD_TYPE];
      final fieldType = fieldType0?.toString().trim().nullIfEmpty;
      final nullable0 = otherData?[K_NULLABLE];
      final nullable = letBool(nullable0);
      return Field(
        fieldName: fieldName,
        fieldType: fieldType,
        nullable: nullable,
      );
    } catch (e) {
      return null;
    }
  }

  //
  //
  //

  factory Field.fromUri(
    Uri? uri,
  ) {
    try {
      return fromUriOrNull(uri)!;
    } catch (e) {
      assert(false, 'Field.fromUri: $e');
      rethrow;
    }
  }

  static Field? fromUriOrNull(
    Uri? uri,
  ) {
    try {
      if (uri != null && uri.path == CLASS) {
        return Field.fromJson(uri.queryParameters);
      } else {
        return Field.b();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final fieldName0 = this.fieldName?.trim().nullIfEmpty;
      final fieldType0 = this.fieldType?.trim().nullIfEmpty;
      final nullable0 = this.nullable;
      final withNulls = <String, dynamic>{
        K_FIELD_NAME: fieldName0,
        K_FIELD_TYPE: fieldType0,
        K_NULLABLE: nullable0,
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, 'Field.toJson: $e');
      rethrow;
    }
  }

  //
  //
  //

  @override
  Field copyWith(Model? other) {
    final a = this.toJson();
    final b = other?.toJson();
    final c = {...a, ...?b};
    return Field.fromJson(c);
  }

  //
  //
  //

  // fieldName.
  String get fieldNameField => this.fieldName!;

  // fieldType.
  String get fieldTypeField => this.fieldType!;

  // nullable.
  bool? get nullableField => this.nullable;
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

enum FieldFields {
  //
  //
  //

  fieldName(
    const Field(
      fieldName: 'fieldName',
      fieldType: 'String',
      nullable: false,
    ),
  ),
  fieldType(
    const Field(
      fieldName: 'fieldType',
      fieldType: 'String',
      nullable: false,
    ),
  ),
  nullable(
    const Field(
      fieldName: 'nullable',
      fieldType: 'bool',
      nullable: true,
    ),
  );

  //
  //
  //

  final Field field;

  //
  //
  //

  const FieldFields(this.field);
}
