//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'example.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelUser extends _ModelUser {
  //
  //
  //

  static const K_ARGS = "args";
  static const K_CONNECTION_UIDS = "connection_uids";
  static const K_DID_SEND_WELCOME_EMAIL = "did_send_welcome_email";
  static const K_EMAIL_SUBSCRIPTIONS = "email_subscriptions";
  static const K_ID = "id";
  static const K_PUSH_SUBSCRIPTIONS = "push_subscriptions";
  static const K_RELATIONSHIP_IDS = "relationship_ids";
  static const K_SMS_SUBSCRIPTIONS = "sms_subscriptions";
  static const K_USER_PUB_ID = "user_pub_id";
  static const K_WHEN_LAST_LOGGED_IN = "when_last_logged_in";

  Set<String>? connectionUids;
  bool? didSendWelcomeEmail;
  Set<String>? emailSubscriptions;
  Set<String>? pushSubscriptions;
  Set<String>? relationshipIds;
  Set<String>? smsSubscriptions;
  String? userPubId;
  DateTime? whenLastLoggedIn;

  //
  //
  //

  ModelUser({
    String? id,
    dynamic args,
    this.connectionUids,
    this.didSendWelcomeEmail,
    this.emailSubscriptions,
    this.pushSubscriptions,
    this.relationshipIds,
    this.smsSubscriptions,
    this.userPubId,
    this.whenLastLoggedIn,
  }) : super._() {
    this.id = id;
    this.args = args;
  }

  //
  //
  //

  ModelUser.unsafe({
    String? id,
    dynamic args,
    this.connectionUids,
    this.didSendWelcomeEmail,
    this.emailSubscriptions,
    this.pushSubscriptions,
    this.relationshipIds,
    this.smsSubscriptions,
    this.userPubId,
    this.whenLastLoggedIn,
  }) : super._() {
    this.id = id;
    this.args = args;
  }

  //
  //
  //

  factory ModelUser.from(
    ModelUser other,
  ) {
    return ModelUser.unsafe()..updateWith(other);
  }

  //
  //
  //

  factory ModelUser.fromJsonString(
    String source,
  ) {
    try {
      final decoded = jsonDecode(source);
      return ModelUser.fromJson(decoded);
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  factory ModelUser.fromJson(
    Map<String, dynamic> input,
  ) {
    try {
      return ModelUser.unsafe(
        args: input[K_ARGS],
        connectionUids: letSet(input[K_CONNECTION_UIDS])
            ?.map(
              (final p0) => p0?.toString().trim().nullIfEmpty,
            )
            .nonNulls
            .nullIfEmpty
            ?.toSet()
            .cast(),
        didSendWelcomeEmail: letBool(input[K_DID_SEND_WELCOME_EMAIL]),
        emailSubscriptions: letSet(input[K_EMAIL_SUBSCRIPTIONS])
            ?.map(
              (final p0) => p0?.toString().trim().nullIfEmpty,
            )
            .nonNulls
            .nullIfEmpty
            ?.toSet()
            .cast(),
        id: input[K_ID]?.toString().trim().nullIfEmpty,
        pushSubscriptions: letSet(input[K_PUSH_SUBSCRIPTIONS])
            ?.map(
              (final p0) => p0?.toString().trim().nullIfEmpty,
            )
            .nonNulls
            .nullIfEmpty
            ?.toSet()
            .cast(),
        relationshipIds: letSet(input[K_RELATIONSHIP_IDS])
            ?.map(
              (final p0) => p0?.toString().trim().nullIfEmpty,
            )
            .nonNulls
            .nullIfEmpty
            ?.toSet()
            .cast(),
        smsSubscriptions: letSet(input[K_SMS_SUBSCRIPTIONS])
            ?.map(
              (final p0) => p0?.toString().trim().nullIfEmpty,
            )
            .nonNulls
            .nullIfEmpty
            ?.toSet()
            .cast(),
        userPubId: input[K_USER_PUB_ID]?.toString().trim().nullIfEmpty,
        whenLastLoggedIn: () {
          final a = input[K_WHEN_LAST_LOGGED_IN];
          return a != null ? DateTime.tryParse(a)?.toUtc() : null;
        }(),
      );
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final withNulls = <String, dynamic>{
        K_ARGS: args,
        K_CONNECTION_UIDS: connectionUids
            ?.map(
              (final p0) => p0?.toString().trim().nullIfEmpty,
            )
            .nonNulls
            .nullIfEmpty
            ?.toList(),
        K_DID_SEND_WELCOME_EMAIL: didSendWelcomeEmail,
        K_EMAIL_SUBSCRIPTIONS: emailSubscriptions
            ?.map(
              (final p0) => p0?.toString().trim().nullIfEmpty,
            )
            .nonNulls
            .nullIfEmpty
            ?.toList(),
        K_ID: id?.toString().trim().nullIfEmpty,
        K_PUSH_SUBSCRIPTIONS: pushSubscriptions
            ?.map(
              (final p0) => p0?.toString().trim().nullIfEmpty,
            )
            .nonNulls
            .nullIfEmpty
            ?.toList(),
        K_RELATIONSHIP_IDS: relationshipIds
            ?.map(
              (final p0) => p0?.toString().trim().nullIfEmpty,
            )
            .nonNulls
            .nullIfEmpty
            ?.toList(),
        K_SMS_SUBSCRIPTIONS: smsSubscriptions
            ?.map(
              (final p0) => p0?.toString().trim().nullIfEmpty,
            )
            .nonNulls
            .nullIfEmpty
            ?.toList(),
        K_USER_PUB_ID: userPubId?.toString().trim().nullIfEmpty,
        K_WHEN_LAST_LOGGED_IN: whenLastLoggedIn?.toUtc()?.toIso8601String(),
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  @override
  T empty<T extends Model>() {
    return ModelUser.unsafe() as T;
  }

  //
  //
  //

  @override
  T copy<T extends Model>() {
    return (ModelUser.unsafe()..updateWith(this)) as T;
  }

  //
  //
  //

  @override
  T copyWith<T extends Model>(
    T other,
  ) {
    if (other is ModelUser) {
      return this.copy<T>()..updateWith(other);
    }
    assert(false);
    return this.copy<T>();
  }

  //
  //
  //

  @override
  T copyWithJson<T extends Model>(
    Map<String, dynamic> other,
  ) {
    if (other.isNotEmpty) {
      return this.copy<T>()..updateWithJson(other);
    }
    return this.copy<T>();
  }

  //
  //
  //

  @override
  void updateWith<T extends Model>(
    T other,
  ) {
    if (other is ModelUser) {
      this.args = other.args ?? this.args;
      this.connectionUids = other.connectionUids ?? this.connectionUids;
      this.didSendWelcomeEmail = other.didSendWelcomeEmail ?? this.didSendWelcomeEmail;
      this.emailSubscriptions = other.emailSubscriptions ?? this.emailSubscriptions;
      this.id = other.id ?? this.id;
      this.pushSubscriptions = other.pushSubscriptions ?? this.pushSubscriptions;
      this.relationshipIds = other.relationshipIds ?? this.relationshipIds;
      this.smsSubscriptions = other.smsSubscriptions ?? this.smsSubscriptions;
      this.userPubId = other.userPubId ?? this.userPubId;
      this.whenLastLoggedIn = other.whenLastLoggedIn ?? this.whenLastLoggedIn;
    } else {
      assert(false);
    }
  }

  //
  //
  //

  @override
  void updateWithJson<T extends Model>(
    Map<String, dynamic> other,
  ) {
    this.updateWith(ModelUser.fromJson(other));
  }
}
