//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'model_with_ref.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelWithRef extends _ModelWithRef {
  //
  //
  //

  static const CLASS_NAME = 'ModelWithRef';

  @override
  String get $className => CLASS_NAME;

  final DataRefModel? ref;

  //
  //
  //

  const ModelWithRef({
    required this.ref,
  });

  //
  //
  //

  factory ModelWithRef.b({
    DataRefModel? ref,
  }) {
    assert(ref != null);
    return ModelWithRef(
      ref: ref,
    );
  }

  //
  //
  //

  factory ModelWithRef.from(
    BaseModel? other,
  ) {
    try {
      return fromOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelWithRef.from: $e');
      rethrow;
    }
  }

  static ModelWithRef? fromOrNull(
    BaseModel? other,
  ) {
    return fromJsonOrNull(other?.toJson())!;
  }

  //
  //
  //

  factory ModelWithRef.of(
    ModelWithRef other,
  ) {
    try {
      return ofOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelWithRef.of: $e');
      rethrow;
    }
  }

  static ModelWithRef? ofOrNull(
    ModelWithRef? other,
  ) {
    return fromJsonOrNull(other?.toJson());
  }

  //
  //
  //

  factory ModelWithRef.fromJsonString(
    String source,
  ) {
    try {
      return fromJsonStringOrNull(source)!;
    } catch (e) {
      assert(false, 'ModelWithRef.fromJsonString: $e');
      rethrow;
    }
  }

  static ModelWithRef? fromJsonStringOrNull(
    String? source,
  ) {
    try {
      if (source!.isNotEmpty) {
        final decoded = jsonDecode(source);
        return ModelWithRef.fromJson(decoded);
      } else {
        return ModelWithRef.b();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  factory ModelWithRef.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return fromJsonOrNull(otherData)!;
    } catch (e) {
      assert(false, 'ModelWithRef.fromJson: $e');
      rethrow;
    }
  }

  static ModelWithRef? fromJsonOrNull(
    Map<String, dynamic>? otherData,
  ) {
    try {
      final ref0 = otherData?['ref'];
      final ref = () {
        final a = letMap<String, dynamic>(ref0);
        return a != null ? DataRefModel.fromJson(a) : null;
      }();
      return ModelWithRef(
        ref: ref,
      );
    } catch (e) {
      return null;
    }
  }

  //
  //
  //

  factory ModelWithRef.fromUri(
    Uri? uri,
  ) {
    try {
      return fromUriOrNull(uri)!;
    } catch (e) {
      assert(false, 'ModelWithRef.fromUri: $e');
      rethrow;
    }
  }

  static ModelWithRef? fromUriOrNull(
    Uri? uri,
  ) {
    try {
      if (uri != null && uri.path == CLASS_NAME) {
        return ModelWithRef.fromJson(uri.queryParameters);
      } else {
        return ModelWithRef.b();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final ref0 = this.ref?.toJson();
      final withNulls = <String, dynamic>{
        'ref': ref0,
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, 'ModelWithRef.toJson: $e');
      rethrow;
    }
  }

  //
  //
  //

  @override
  ModelWithRef copyWith(BaseModel? other) {
    final a = this.toJson();
    final b = other?.toJson();
    final c = {...a, ...?b};
    return ModelWithRef.fromJson(c);
  }

  //
  //
  //

  // ref.
  DataRefModel get refField => this.ref!;
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

enum ModelWithRefFields {
  //
  //
  //

  ref(
    const Field(
      fieldName: 'ref',
      fieldType: 'DataRefModel',
      nullable: false,
    ),
  );

  //
  //
  //

  final Field field;

  //
  //
  //

  const ModelWithRefFields(this.field);

  //
  //
  //

  String get name => this.field.fieldName!;
}
