##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## 🇽🇾🇿 & Dev
##
## Licencing details are in the LICENSE file in the root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

include: package:lints/recommended.yaml

## ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

linter:
  rules:
    avoid_web_libraries_in_flutter: true
    constant_identifier_names: false
    file_names: false
    non_constant_identifier_names: false
    omit_local_variable_types: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    require_trailing_commas: true
    unnecessary_this: false
    camel_case_types: false
    library_private_types_in_public_api: false

analyzer:
  exclude:
    - build/**

  errors:
    always_declare_return_types: error
    avoid_renaming_method_parameters: error
    avoid_type_to_string: error
    depend_on_referenced_packages: error
    flutter_style_todos: error
    no_leading_underscores_for_local_identifiers: error
    prefer_final_in_for_each: error
    prefer_relative_imports: error
    unnecessary_new: error
    unrelated_type_equality_checks: error
    use_key_in_widget_constructors: error
