##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## 🇽🇾🇿 & Dev
##
## Licencing details are in the LICENSE file in the root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: xyz_gen_annotations
description: This package includes the annotations for the xyz_gen package. See https://pub.dev/packages/xyz_gen for more information.
repository: https://github.com/robmllze/xyz_gen_annotations
version: 0.49.0
publish_to: none

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.4.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  xyz_utils: ">=0.60.0 <1.0.0"
  collection: ^1.18.0
  equatable: ^2.0.5
  meta: ^1.11.0

## -----------------------------------------------------------------------------

dependency_overrides:
  # TODO: Comment out these lines if you don't have these packages at the
  # respective paths. They are included for development purposes to allow
  # simultaneous work on this package and its dependencies.
  xyz_utils:
    path: ../../xyz_utils

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^3.0.0
