##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## 🇽🇾🇿 & Dev
##
## Licencing details are in the LICENSE file in the root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: xyz_gen_annotations
description: This package includes the annotations for the xyz_gen package. See https://pub.dev/packages/xyz_gen for more information.
repository: https://github.com/robmllze/xyz_gen_annotations
version: 0.39.0

## -----------------------------------------------------------------------------

environment:
  sdk: ">= 3.3.1 < 4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  xyz_utils: ^0.54.0
  collection: ^1.18.0
  equatable: ^2.0.5
  meta: ^1.11.0

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^3.0.0
