#.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## XYZ Gen
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#.title~

name: xyz_gen_annotations
description: Includes annotations and supporting utilities for the xyz_gen package.
repository: https://github.com/robmllze/xyz_gen_annotations
version: 0.3.1

## -----------------------------------------------------------------------------

environment:

  sdk: ^3.0.0

## -----------------------------------------------------------------------------

dependencies:
  collection: ^1.18.0
  xyz_utils: ^0.34.1

## -----------------------------------------------------------------------------

dev_dependencies:

  lints: ^3.0.0


