//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'data_ref.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class DataRef extends _DataRef {
  //
  //
  //

  static const K_COLLECTION = 'collection';
  static const K_ID = 'id';
  static const K_TABLE_NAME = 'table_name';

  static const CLASS = 'DataRef';

  @override
  String get $class => CLASS;

  List<String>? collection;
  String? id;
  String? tableName;

  //
  //
  //

  DataRef.empty();

  //
  //
  //

  factory DataRef({
    List<String>? collection,
    String? id,
    String? tableName,
  }) {
    return DataRef.b(
      collection: collection,
      id: id,
      tableName: tableName,
    );
  }

  //
  //
  //

  DataRef.b({
    this.collection,
    this.id,
    this.tableName,
  }) {}

  //
  //
  //

  factory DataRef.from(
    Model? other,
  ) {
    try {
      return fromOrNull(other)!;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  static DataRef? fromOrNull(
    Model? other,
  ) {
    return fromJsonOrNull(
      letAs<GenericModel>(other)?.data ?? other?.toJson(),
    )!;
  }

  //
  //
  //

  factory DataRef.of(
    DataRef other,
  ) {
    try {
      return ofOrNull(other)!;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  static DataRef? ofOrNull(
    DataRef? other,
  ) {
    return fromJsonOrNull(other?.toJson());
  }

  //
  //
  //

  factory DataRef.fromJsonString(
    String source,
  ) {
    try {
      return fromJsonStringOrNull(source)!;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  static DataRef? fromJsonStringOrNull(
    String? source,
  ) {
    try {
      if (source!.isNotEmpty) {
        final decoded = jsonDecode(source);
        return DataRef.fromJson(decoded);
      } else {
        return DataRef.empty();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  factory DataRef.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return fromJsonOrNull(otherData)!;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  static DataRef? fromJsonOrNull(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return DataRef.empty()
        ..$collection = otherData?[K_COLLECTION]
        ..$id = otherData?[K_ID]
        ..$tableName = otherData?[K_TABLE_NAME];
    } catch (e) {
      return null;
    }
  }

  //
  //
  //

  factory DataRef.fromUri(
    Uri? uri,
  ) {
    try {
      return fromUriOrNull(uri)!;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  static DataRef? fromUriOrNull(
    Uri? uri,
  ) {
    try {
      if (uri != null && uri.path == CLASS) {
        return DataRef.fromJson(uri.queryParameters);
      } else {
        return DataRef.b();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final withNulls = <String, dynamic>{
        K_COLLECTION: this.$collection,
        K_ID: this.$id,
        K_TABLE_NAME: this.$tableName,
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  @override
  T empty<T extends Model>() {
    return DataRef.b() as T;
  }

  //
  //
  //

  @override
  T copy<T extends Model>() {
    return (DataRef.b()..updateWith(this)) as T;
  }

  //
  //
  //

  @override
  void updateWithJson(
    Map<String, dynamic>? otherData,
  ) {
    if (otherData != null && otherData.isNotEmpty) {
      final other = DataRef.fromJson(otherData);
      if (other.collection != null) {
        this.collection = other.collection!;
      }
      if (other.id != null) {
        this.id = other.id!;
      }
      if (other.tableName != null) {
        this.tableName = other.tableName!;
      }
    }
  }

  //
  //
  //

  // collection.
  List<String>? get collectionField => this.collection;
  set collectionField(List<String>? v) => this.collection = v;
  @protected
  dynamic get $collection => this
      .collection
      ?.map(
        (p0) => p0?.toString().trim().nullIfEmpty,
      )
      .nonNulls
      .nullIfEmpty
      ?.toList();
  @protected
  set $collection(v) => this.collection = letList(v)
      ?.map(
        (p0) => p0?.toString().trim().nullIfEmpty,
      )
      .nonNulls
      .nullIfEmpty
      ?.toList()
      .cast();

  // id.
  String? get idField => this.id;
  set idField(String? v) => this.id = v;
  @protected
  dynamic get $id => this.id?.toString().trim().nullIfEmpty;
  @protected
  set $id(v) => this.id = v?.toString().trim().nullIfEmpty;

  // tableName.
  String? get tableNameField => this.tableName;
  set tableNameField(String? v) => this.tableName = v;
  @protected
  dynamic get $tableName => this.tableName?.toString().trim().nullIfEmpty;
  @protected
  set $tableName(v) => this.tableName = v?.toString().trim().nullIfEmpty;
}
