//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

export 'annotations/field.dart';
export 'annotations/generate_makeups.dart';
export 'annotations/generate_model.dart';
export 'annotations/generate_screen_bindings.dart';
export 'annotations/generate_type_utils.dart';
export 'annotations/property.dart';
export 'annotations/test_annotation.dart';
export 'models/data_model/data_model.dart';
export 'models/generic_model.dart';
export 'models/model.dart';
export 'utils/prep_value.dart';
export 'utils/this_model.dart';
export 'utils/types.dart';
