//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'generic_model.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class GenericModel extends Model {
  //
  //
  //

  static const CLASS = 'GenericModel';
  static const MODEL_ID = 'generic_model';

  static const K_DATA = 'data';
  static const K_ID = 'id';

  Map<String, dynamic>? data;

  //
  //
  //

  GenericModel({
    String? id,
    this.data,
  }) {
    this.id = id;
  }

  //
  //
  //

  GenericModel.unsafe({
    String? id,
    this.data,
  }) {
    this.id = id;
  }

  //
  //
  //

  factory GenericModel.from(
    Model? other,
  ) {
    return GenericModel.unsafe()..updateWith(other);
  }

  //
  //
  //

  factory GenericModel.of(
    GenericModel? other,
  ) {
    return GenericModel.unsafe()..updateWith(other);
  }

  //
  //
  //

  factory GenericModel.fromJsonString(
    String? source,
  ) {
    try {
      if (source != null && source.isNotEmpty) {
        final decoded = jsonDecode(source);
        return GenericModel.fromJson(decoded);
      } else {
        return GenericModel.unsafe();
      }
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  factory GenericModel.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return GenericModel.unsafe(
        data: letMap(otherData?[K_DATA])
            ?.map(
              (final p0, final p1) => MapEntry(
                p0?.toString().trim().nullIfEmpty,
                p1,
              ),
            )
            .nonNulls
            .nullIfEmpty
            ?.cast(),
        id: otherData?[K_ID]?.toString().trim().nullIfEmpty,
      );
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final withNulls = <String, dynamic>{
        K_DATA: data
            ?.map(
              (final p0, final p1) => MapEntry(
                p0?.toString().trim().nullIfEmpty,
                p1,
              ),
            )
            .nonNulls
            .nullIfEmpty,
        K_ID: id?.toString().trim().nullIfEmpty,
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  @override
  T empty<T extends Model>() {
    return GenericModel.unsafe() as T;
  }

  //
  //
  //

  @override
  T copy<T extends Model>() {
    return (GenericModel.unsafe()..updateWith(this)) as T;
  }

  //
  //
  //

  @override
  void updateWithJson(
    Map<String, dynamic>? otherData,
  ) {
    if (otherData != null && otherData.isNotEmpty) {
      final other = GenericModel.fromJson(otherData);
      other.data != null ? this.data = other.data : null;
      other.id != null ? this.id = other.id : null;
    }
  }
}
