//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'data_model.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class DataModel extends _DataModel {
  //
  //
  //

  static const K_DATA = 'data';

  static const CLASS = 'DataModel';

  @override
  String get $class => CLASS;

  Map<String, dynamic>? data;

  //
  //
  //

  DataModel.empty();

  //
  //
  //

  factory DataModel({
    Map<String, dynamic>? data,
  }) {
    return DataModel.b(
      data: data,
    );
  }

  //
  //
  //

  DataModel.b({
    this.data,
  }) {}

  //
  //
  //

  factory DataModel.from(
    Model? other,
  ) {
    try {
      return fromOrNull(other)!;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  static DataModel? fromOrNull(
    Model? other,
  ) {
    return fromJsonOrNull(
      letAs<DataModel>(other)?.data ?? other?.toJson(),
    )!;
  }

  //
  //
  //

  factory DataModel.of(
    DataModel other,
  ) {
    try {
      return ofOrNull(other)!;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  static DataModel? ofOrNull(
    DataModel? other,
  ) {
    return fromJsonOrNull(other?.toJson());
  }

  //
  //
  //

  factory DataModel.fromJsonString(
    String source,
  ) {
    try {
      return fromJsonStringOrNull(source)!;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  static DataModel? fromJsonStringOrNull(
    String? source,
  ) {
    try {
      if (source!.isNotEmpty) {
        final decoded = jsonDecode(source);
        return DataModel.fromJson(decoded);
      } else {
        return DataModel.empty();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  factory DataModel.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return fromJsonOrNull(otherData)!;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  static DataModel? fromJsonOrNull(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return DataModel.empty()..$data = otherData;
    } catch (e) {
      return null;
    }
  }

  //
  //
  //

  factory DataModel.fromUri(
    Uri? uri,
  ) {
    try {
      return fromUriOrNull(uri)!;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  static DataModel? fromUriOrNull(
    Uri? uri,
  ) {
    try {
      if (uri != null && uri.path == CLASS) {
        return DataModel.fromJson(uri.queryParameters);
      } else {
        return DataModel.b();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final withNulls = <String, dynamic>{
        K_DATA: this.$data,
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, e);
      rethrow;
    }
  }

  //
  //
  //

  @override
  T empty<T extends Model>() {
    return DataModel.b() as T;
  }

  //
  //
  //

  @override
  T copy<T extends Model>() {
    return (DataModel.b()..updateWith(this)) as T;
  }

  //
  //
  //

  @override
  void updateWithJson(
    Map<String, dynamic>? otherData,
  ) {
    if (otherData != null && otherData.isNotEmpty) {
      final other = DataModel.fromJson(otherData);
      if (other.data != null) {
        this.data = other.data!;
      }
    }
  }

  //
  //
  //

  // data.
  Map<String, dynamic>? get dataField => this.data;
  set dataField(Map<String, dynamic>? v) => this.data = v;
  @protected
  dynamic get $data => this
      .data
      ?.map(
        (p0, p1) => MapEntry(
          p0?.toString().trim().nullIfEmpty,
          p1,
        ),
      )
      .nonNulls
      .nullIfEmpty;
  @protected
  set $data(v) => this.data = letMap(v)
      ?.map(
        (p0, p1) => MapEntry(
          p0?.toString().trim().nullIfEmpty,
          p1,
        ),
      )
      .nonNulls
      .nullIfEmpty
      ?.cast();
}
