//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

export 'src/all_src.g.dart';
export 'src/annotations/field.dart';
export 'src/annotations/generate_makeups.dart';
export 'src/annotations/generate_model.dart';
export 'src/annotations/generate_screen_configuration.dart';
export 'src/annotations/parameter.dart';
export 'src/annotations/test_annotation.dart';
export 'src/utils/generic_model.dart';
export 'src/utils/model.dart';
export 'src/utils/prep_value.dart';
export 'src/utils/this_model.dart';
export 'src/utils/types.dart';
export 'xyz_gen_annotations.dart';
